###movies index
GET http://localhost:3000/movies


###movies create
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "Kill Bill",
  "year": "2005",
  "plot": "uma",
  "director": "QT",
  "english": true 
  
}

###movies show
GET http://localhost:3000/movies/4

###movies patch
PATCH http://localhost:3000/movies/8
Content-Type: application/json

{
  "title": "The Matrix",
  "year": "1999",
  "plot": "take",
  "director": "Wachaoski",
  "english": true
}

###movies delete
DELETE http://localhost:3000/movies/4
Content-Type: application/json

