### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Bagel",
  "email": "bagel@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}