###Actor index
GET http://localhost:3000/actors




###Actor create
POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "B",
  "last_name": "Saget",
  "known_for": "Full House",
  "gender": "male",
  "age": 55
}

###Actor show
GET http://localhost:3000/actors/5

###Actor patch
PATCH http://localhost:3000/actors/8
Content-Type: application/json

{
  "first_name": "Homer",
  "last_name": "Simpson",
  "known_for": "The Simsons",
  "gender": "male",
  "age": 45,
  "movie_id": 6
}

###Actor delete
DELETE http://localhost:3000/actors/9
Content-Type: application/json

